apiVersion: v1
kind: ConfigMap
metadata:
  name: common-rabbit-config
data:
  # Configuração do RabbitMQ
  RabbitMQ__HostName: "rabbitmq.default.svc.cluster.local"
  RabbitMQ__UserName: "guest"
  RabbitMQ__Password: "guest"
  RabbitMQ__ExchangeAdd: "Fase3.Contatos.Add"
  RabbitMQ__ExchangeUpdate: "Fase3.Contatos.Update"
  RabbitMQ__ExchangeDelete: "Fase3.Contatos.Delete"
  RabbitMQ__Port: "5672"
  RabbitMQ__ConnectionString: "amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672"