apiVersion: apps/v1
kind: Deployment
metadata:
  name: contatos-api
  labels:
    app: contatos-api
  annotations:
    description: "Api de contatos"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contatos-api
  template:
    metadata:
      labels:
        app: contatos-api
    spec:
      containers:
      - name: contatos-api
        image: luisfernandofernandes/postech-contatos-api:1.0
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
