apiVersion: apps/v1
kind: Deployment
metadata:
  name: contatos-update-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contatos-update-service
  template:
    metadata:
      labels:
        app: contatos-update-service
    spec:
      containers:
      - name: contatos-update-service
        image: hajimemori/postech-contatos-update-service:1.0
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: contatos-update-config
        - configMapRef:
            name: common-rabbit-config

---

apiVersion: v1
kind: Service
metadata:
  name: contatos-update-service
spec:
  selector:
    app: contatos-update-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: contatos-update-config
data:

  # Configuração do banco de dados
  ConnectionStrings__DefaultConnection: "Server=154.38.172.208,52439;Database=ContatoFase3;User Id=sa;Password=Fiap2024$;TrustServerCertificate=True;"

  # Configuração do RabbitMQ
  RabbitMQ__QueueName: "Fase3.Contatos.UpdatetoDataBase"
  
  # Hosts permitidos
  AllowedHosts: "*"
