apiVersion: apps/v1
kind: Deployment
metadata:
  name: contatos-delete-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contatos-delete-service
  template:
    metadata:
      labels:
        app: contatos-delete-service
    spec:
      containers:
      - name: contatos-delete-container
        image: hajimemori/contatos-delete-service:1.1
        ports:
        - containerPort: 5003
        envFrom:
        - configMapRef:
            name: contatos-delete-config
        - configMapRef:
            name: common-rabbit-config

---

apiVersion: v1
kind: Service
metadata:
  name: contatos-delete-service
spec:
  selector:
    app: contatos-delete-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: ClusterIP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: contatos-delete-config
data:

  # Configuração do banco de dados
  ConnectionStrings__DefaultConnection: "Server=154.38.172.208,52439;Database=ContatoFase3;User Id=sa;Password=Fiap2024$;TrustServerCertificate=True;"

  # Configuração do RabbitMQ
  RabbitMQ__QueueName: "Fase3.Contatos.DeletetoDataBase"
  
  # Hosts permitidos
  AllowedHosts: "*"
