@hostname = http://localhost:5196/api
@controller = Contato

Post {{hostname}}/{{controller}}
Content-Type: application/json
Accept: application/json

{
    "DDDId": "11",
    "UF": "SP",
    "Regiao": "São Paulo"
}